/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(crc32_check.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(87001c0fd4a305c25cfac31eefea255c)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <demonstrator/crc32_check.h>
// pydoc.h is automatically generated in the build directory
#include <crc32_check_pydoc.h>

void bind_crc32_check(py::module& m)
{

    using crc32_check    = ::gr::demonstrator::crc32_check;


    py::class_<crc32_check, gr::block, gr::basic_block,
        std::shared_ptr<crc32_check>>(m, "crc32_check", D(crc32_check))

        .def(py::init(&crc32_check::make),
           py::arg("n_packets"),
           py::arg("n_sym"),
           py::arg("n_user"),
           D(crc32_check,make)
        )
        



        ;




}








