/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(diff_encoder_qpsk_cc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(4264f79298d0169fe75cf7609973e65e)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <demonstrator/diff_encoder_qpsk_cc.h>
// pydoc.h is automatically generated in the build directory
#include <diff_encoder_qpsk_cc_pydoc.h>

void bind_diff_encoder_qpsk_cc(py::module& m)
{

    using diff_encoder_qpsk_cc    = ::gr::demonstrator::diff_encoder_qpsk_cc;


    py::class_<diff_encoder_qpsk_cc, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<diff_encoder_qpsk_cc>>(m, "diff_encoder_qpsk_cc", D(diff_encoder_qpsk_cc))

        .def(py::init(&diff_encoder_qpsk_cc::make),
           D(diff_encoder_qpsk_cc,make)
        )
        



        ;




}








