/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(header_detector_bb.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(31c15730ec651ff9823e29a0b766513e)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <demonstrator/header_detector_bb.h>
// pydoc.h is automatically generated in the build directory
#include <header_detector_bb_pydoc.h>

void bind_header_detector_bb(py::module& m)
{

    using header_detector_bb    = ::gr::demonstrator::header_detector_bb;


    py::class_<header_detector_bb, gr::block, gr::basic_block,
        std::shared_ptr<header_detector_bb>>(m, "header_detector_bb", D(header_detector_bb))

        .def(py::init(&header_detector_bb::make),
           py::arg("n_payload_bytes"),
           D(header_detector_bb,make)
        )
        



        ;




}








