/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(tag_sink.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(46b3b8e31f1fa316ca1349abfaca6b91)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <demonstrator/tag_sink.h>
// pydoc.h is automatically generated in the build directory
#include <tag_sink_pydoc.h>

void bind_tag_sink(py::module& m)
{

    using tag_sink    = ::gr::demonstrator::tag_sink;


    py::class_<tag_sink, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<tag_sink>>(m, "tag_sink", D(tag_sink))

        .def(py::init(&tag_sink::make),
           py::arg("filename"),
           py::arg("tag_key"),
           D(tag_sink,make)
        )
        



        ;




}








